<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0-rc.1.21451.13" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0-rc.1.21451.13" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="6.0.0-rc.1.21451.13" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="System.Net.Http.Json" Version="6.0.0-rc.1.21451.13" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\UserManagements\" />
    <Folder Include="Services\ShopManagements\" />
    <Folder Include="Services\ShippingManagements\" />
    <Folder Include="Services\ReviewManagements\" />
    <Folder Include="Services\ReceiptManagements\" />
    <Folder Include="Services\PaymentManagements\" />
  </ItemGroup>

</Project>
